### ISSUE TITLE
NPM Install Fails

### ISSUE THREAD

**Issue by aualdrich** [Dahs81/ace-snippet-ext-example#1]
When trying to run npm install, I get this error:

```
Failed to parse json
npm ERR! Trailing comma in object at 10:3
npm ERR!   }
npm ERR!   ^
npm ERR! File: /Users/aualdrich/dev/ace-snippet-ext-example/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
```

**Comment by Dahs81** [comment]
I fixed that bug.  Should work now.

**Comment by Dahs81** [comment]
I also updated this project so that it works correctly.  I haven't touched it in over a year.  I updated the README, so it should be easier to understand what I'm doing.  Hopefully that helps.

Let me know if you run into any other issues.
